# Generated by Django 5.1.7 on 2025-03-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_remove_trip_description_trip_distance_trip_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
