# Generated by Django 5.1.1 on 2025-03-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_alter_trip_distance_alter_trip_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='duration',
        ),
        migrations.AddField(
            model_name='trip',
            name='requiredBreaks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='requiredRests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='totalDistance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='totalDuration',
            field=models.FloatField(default=0.0),
        ),
    ]
